### PR TITLE
Use `Sidekiq::JobRecord` for Sidekiq >= v6.2.2

### LINKED ISSUE #4: Sidekiq v6.2.2 renamed `Job` to `JobRecord`
See https://github.com/mperham/sidekiq/commit/f1b24da9c225a5512120514d32a5348760e92f3a

More interestingly, a *new* `Sidekiq::Job` got added – https://github.com/mperham/sidekiq/commit/8e36432662421e79cf14096e9467666b6827f82d –  which is the old `Sidekiq::Worker`, it seems.

Looks like they wanted to break everyone using the old `Sidekiq::Job` now so it gets noticed. Really bold step IMO (could have been deprecated at least for a minor version), but it is what it is.

See https://github.com/mperham/sidekiq/discussions/4971 for the full discussion.

Just a heads up from me for now.

### PR DESCRIPTION
**Pull request by doits**
fixes #4

~~There will be more changes necessary when `Sidekiq::Worker` will be renamed to `Sidekiq::Job` (planned for Sidekiq v6.3.0 afaik), but until then it should work.~~ Edit: Shouldn't be necessary, see comment below (https://github.com/kenaniah/sidekiq-status/pull/5#issuecomment-905717391)

### CODE REVIEW

**Comment by deikka** [comment]
Hi. Are you merging this branch anytime soon? @doits 
Thanks!

**Comment by doits** [comment]
If I could I would :-) Waiting for @kenaniah

**Comment by joe1chen** [comment]
@kenaniah There are several people waiting for this to be merged. Can you help?

**Comment by joe1chen** [comment]
Nevermind, I just saw that this was fixed.

**Comment by kenaniah** [comment]
Hi all. My apologies, this PR was buried in my inbox until I noticed the same issue independently today. Version 2.1.0 resolves this issue, and I will update the change log shortly. Thanks again for bringing this to my attention.

**Pull request closed without merging**
