### PR TITLE
Add Sidekiq 7 support

### PR DESCRIPTION
**Pull request by soberstadt**
Welp, I fixed it, but then Travis cut us off :(

### CODE REVIEW

**Comment by pasl** [comment]
Hi

I have tested my app with this commit 
  remote: https://github.com/anedot/sidekiq-status
  revision: 6ffd4c96f9bd4d52d8c304ee5de60d4ec2b5685b
  branch: sidekiq-7

Everything seems to works fine but specifying expiration with Duration (ex: 2.days) throws this error:

   TypeError: Unsupported command argument type: ActiveSupport::Duration

If we put integer (in seconds) it work.

Not really sure but I think this is a sidekiq issue.

**Comment by soberstadt** [comment]
That was a change that I had to make inside our app config (change the expiration to seconds instead of the duration).

**Comment by kenaniah** [comment]
So I have apparently ran out of OSS credits at TravisCI -- the best path forward might be to migrate this repository over to GitHub actions for CI purposes. I'll create a new PR for this, which should hopefully solve the CI issues going forward.

**Comment by kenaniah** [comment]
A huge thank you to @soberstadt! Unfortunately, I had to migrate CI over to GitHub Actions and drop support for Sidekiq 5.x in the process (via #25), but we're now building. I am going to release as v3.0.0.

**Pull request closed without merging**
